name: Build React App

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches: ["main"]
  # 允许你在 GitHub 界面手动点击按钮触发
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建议使用 LTS 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci # 比 npm install 更稳定，适合 CI 环境

      # 4. 执行构建命令 (生成 index.html 和 assets)
      - name: Build project
        run: npm run build

      # 5. 【方案A】如果你只是想下载编译好的文件：
      # 这步会把构建产物打包成一个压缩包，在 Action 页面下载
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build-files
          # 注意：Vite 默认输出目录是 dist，CRA 默认是 build
          # 请根据你的实际情况修改下面的路径
          path: dist/ 